"""initial schema: users, watches, price_history, ingestion_jobs, api_quota

Revision ID: b8038a261297
Revises: 
Create Date: 2026-08-18 23:02:07.500304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8038a261297'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_quota',
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('calls_used', sa.Integer(), nullable=False),
    sa.Column('calls_limit', sa.Integer(), nullable=True),
    sa.Column('window_start', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('provider')
    )
    op.create_table('ingestion_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_slug', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('stage', sa.String(length=40), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ingestion_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingestion_jobs_product_slug'), ['product_slug'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('google_sub', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('google_sub')
    )
    op.create_table('watches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product', sa.String(length=500), nullable=False),
    sa.Column('product_url', sa.String(length=1000), nullable=True),
    sa.Column('baseline_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('target_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('last_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('last_price_text', sa.String(length=120), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('notified', sa.Boolean(), nullable=False),
    sa.Column('next_check_at', sa.DateTime(), nullable=True),
    sa.Column('last_checked', sa.DateTime(), nullable=True),
    sa.Column('last_decision', sa.Text(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('watches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_watches_next_check_at'), ['next_check_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_watches_user_id'), ['user_id'], unique=False)

    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('watch_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['watch_id'], ['watches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_history_watch_id'), ['watch_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_history_watch_id'))

    op.drop_table('price_history')
    with op.batch_alter_table('watches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watches_user_id'))
        batch_op.drop_index(batch_op.f('ix_watches_next_check_at'))

    op.drop_table('watches')
    op.drop_table('users')
    with op.batch_alter_table('ingestion_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingestion_jobs_product_slug'))

    op.drop_table('ingestion_jobs')
    op.drop_table('api_quota')
    # ### end Alembic commands ###
